name: Call a reusable workflow

on:
  [push, workflow_dispatch]

jobs:
  set-inputs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat inputs.json
      - id: set_var
        run: |
          content=`cat inputs.json`
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          echo "::set-output name=inputJson::$content"
      - run: |
          echo "${{ steps.set_var.outputs.inputJson }}"
  
  call-workflow:
    needs: set-inputs
    uses: hannnnk1231/testActions/.github/workflows/test.yml@main
    with:
      username: ${{ needs.set-inputs.outputs.inputJson }}
